project:
  type: website
  pre-render: assets/scripts/build_audio_file_structure.py
  post-render: assets/scripts/copy_audio_content.py

website:
  title: "jeanlouppecquais.com"
  navbar:
    right:
      # - training.qmd
      - music.qmd
      - blog.qmd
      - text: Projets
        menu:
        - text: Outwards
          href: https://www.outwardsmusic.com/
          target: _blank
        - text: Burger Bang
          href: https://www.youtube.com/@burgerbang
          target: _blank
        - text: Pompéi
          href: https://360prod.fr/collab/pompei
          target: _blank
        - text: Guide pratique des techniques du son
          href: https://doc.jeanlouppecquais.com/
          target: _blank

format:
  html:
    theme: cosmo
    css: assets/styles/common.css
    page-layout: full

lang: fr
language:
  title-block-author-single: Auteur

