name: Deploy via FTP

on:
  push:
    branches:
      - main
  schedule:
      - cron:  '0 8 * * *' #every day at 8 am

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
    
          - uses: actions/checkout@v1
            with:
              submodules: recursive

          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
              hugo-version: 'latest'
              extended: true

          - name: Build CV
            uses: xu-cheng/latex-action@v2
            with:
              root_file: |
                assets/cv-latex/cv.tex

          - name: Build site
            run: hugo --gc --minify
    
          - name: FTP site
            uses: SamKirkland/FTP-Deploy-Action@v4.3.4
            with:
              server: ftp.cluster028.hosting.ovh.net
              username: jeanloupez
              password: ${{ secrets.FTP_PASSWORD }}
              local-dir: ./public/
              server-dir: ./www/
            #   git-ftp-args: --insecure --all